# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c2bdaea8782ab2ba4737451069db70dfffef87df52de6e6f3ca874064d77c2905171a4564d7b4277f7308654c77e42c2633598a0785dab29dbd33f134f0387

test:
  secret_key_base: 37dc252556ae04fb6b5d716ed7d7199eb921144117af52b56d799c9a13886f7489eb9b1e68ab2c03a61fe39a764511d2303b56702cb8566379fa993237f7c027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
